### ISSUE TITLE
可以用在 Y7000P 2020 上吗

### ISSUE THREAD

**Issue by StarOnTheSky** [gclm/Hackintosh-LEGION-Y7000P-I7-9750H#23]
配置:
型号: 82AX
CPU: i7 10750H
GPU: RTX2060 (屏蔽)
硬盘: PM981a (屏蔽)
网卡: AX201
目前测试结果: 能正常启动,但是会出现显卡屏蔽异常,风扇全速运转,导致不久后电脑自动关机,开机后 BIOS 的性能模式被重置.

**Comment by LoveGlaze** [comment]
切换显卡模式为混和模式

**Comment by LoveGlaze** [comment]
> 配置: 型号: 82AX CPU： i7 10750H GPU: RTX2060 (屏蔽) 硬盘: PM981a (屏蔽) 网卡: AX201 目前测试结果: 能正常启动,但是会出现显卡屏蔽异常,风扇全速运转,导致不久后电脑自动关机,开机后 BIOS 的性能模式被重置.

切换显卡为混合模式

**Comment by LoveGlaze** [comment]
981一堆问题，换了吧，群里好像有10代的，你可以问问
