### ISSUE TITLE
cpu识别不正确 i7被识别成i9

### ISSUE THREAD

**Issue by DxSummer** [gclm/Hackintosh-LEGION-Y7000P-I7-9750H#3]
机型：y7000p 2019
 处理器              英特尔 Core i7-9750H @ 2.60GHz 六核
  主板                联想 LNVNB161216 ( 300 Series 芯片组 Family - A30D )
  显卡                Nvidia GeForce GTX 1660 Ti ( 6 GB / 联想 )
  内存                8 GB ( 镁光 DDR4 2666MHz )
  主硬盘              三星 MZVLB1T0HBLR-000L2 ( 1024 GB / 固态硬盘 )
  显示器              京东方 BOE084D ( 15.5 英寸  )
  声卡                英特尔 High Definition Audio 控制器
  网卡                英特尔 Wireless-AC 9560

**Comment by gclm** [comment]
发个截图看看

**Comment by gclm** [comment]
![image](https://user-images.githubusercontent.com/27618687/76592339-fc5b5880-652d-11ea-8630-b91d0e086b39.png)

**如果如截图所示，是正常现象不用在意**

**Comment by DxSummer** [comment]
![QQ20200312-223647](https://user-images.githubusercontent.com/49343733/76593680-3be55e80-64b4-11ea-9183-2be00df1c6a0.png)

**Comment by DxSummer** [comment]
大神 触摸板也不能用

**Comment by gclm** [comment]
我看一下吧。目前预估你的触摸板驱动和我不一样，目前我的触摸板是完美的。所以有驱动出现兼容行问题

**Comment by DxSummer** [comment]
谢谢了 我ok了 我替换了触控板驱动 开启pm981当作辅助磁盘 开启了ac9560网卡的蓝牙  目前没有问题

**Comment by gclm** [comment]
也就是目前你的efi 已经可以正常使用了对吧，如果事的话方便把你的efi 分享一下呢。我集成到这个项目中解决你说的你的平台不支持触摸板的情况

**Comment by gclm** [comment]
或者请你发起 pr

**Comment by DxSummer** [comment]
好的
TA分享了文件给你，在奶牛快传首页（cowtransfer.com）输入取件码：epnrpw (24小时内有效) 查看文件列表，或直接点击取件链接：https://c-t.work/s/060ac93e0bfc4d 查看文件列表

**Comment by gclm** [comment]
![image](https://user-images.githubusercontent.com/27618687/76603813-99c38600-6548-11ea-9f29-5a0f97ae0967.png)

**Comment by gclm** [comment]
密码错误

**Comment by DxSummer** [comment]
112233
