### ISSUE TITLE
安装了屏蔽981的补丁 仍然不能屏蔽pm981

### ISSUE THREAD

**Issue by DxSummer** [gclm/Hackintosh-LEGION-Y7000P-I7-9750H#4]
SSDT-DNVMe.aml

**Comment by gclm** [comment]
1. 你是用的是我的efi吗？
2. 目前我的efi 自带屏蔽981
3.  pm981，屏蔽不仅需要aml 还需要相应的text 进行配合

**Comment by gclm** [comment]
建议你直接使用我的efi 进行测试安装就ok了

**Comment by DxSummer** [comment]
嗯嗯 用的你的efi 981固态还能看到
未改动的efi

**Comment by DxSummer** [comment]
![99C507CA-BFB7-40A9-A7B8-B13144CD86F6](https://user-images.githubusercontent.com/49343733/76684730-63216480-6649-11ea-8551-49ff2ec320ed.png)

**Comment by gclm** [comment]
另外pm 981无法进行正常安装，屏蔽只是为了不影响作为数据盘使用的

**Comment by DxSummer** [comment]
我mac安装在西数的硬盘 然后可以看到pm981

**Comment by gclm** [comment]
建议自行更换其他ssd 或 如果存在机械硬盘请安装到机械硬盘，如果非要强制安装到 pm981 上的话，请自行远景爬楼。谢谢

**Comment by DxSummer** [comment]
哦哦 好的 打扰了 谢谢啦

**Comment by gclm** [comment]
你理解中的屏蔽是不是 在MAC 完全不显示这个硬盘对吧。如果是的话预计你理解的和我有偏差

**Comment by DxSummer** [comment]
我以前用的另外一个efi+SSDT-DNVMe.aml补丁 在mac看不到pm981 
用这个efi可以看到981 并且能打开981的分区 然后 我待机一会儿 电脑自己重启了

**Comment by DxSummer** [comment]
我以为屏蔽是 在MAC 完全不显示981这个硬盘

**Comment by gclm** [comment]
那估计不好意思了，目前这个需求无法满足了，你可以看看其他人的efi，目前这个 efi 屏蔽指的是可以在pm981 上运行mac 系统或者不影响pm981作为数据盘，另外对于你说的睡眠重启，建议自行爬墙解决。因为型号存在差异，睡眠重启无法保证全部通用。目前光使用这个efi 的话，经过我本人半年多的使用，暂时没发现这个情况

**Comment by gclm** [comment]
如果你解决了这个问题的话欢迎自行pr 谢谢你的支持

**Comment by DxSummer** [comment]
好哒 你电脑可以快捷键调节亮度吗 如果不行我给你我的那个补丁

**Comment by DxSummer** [comment]
谢谢了 这么晚打扰了

**Comment by gclm** [comment]
可以，不过需要设置一下快捷键，目前我使用的不是小键盘控制亮度

**Comment by gclm** [comment]
如果你采用的是小键盘的话，希望可以发给我一份
