### ISSUE TITLE
正式版v2.5 笔记本自带键盘不能用

### ISSUE THREAD

**Issue by LanJD** [gclm/Hackintosh-LEGION-Y7000P-I7-9750H#40]
配置：2019款 y7000，第九代i5
使用仓库最新v2.5版本oc引导，使用MacRecovery在线安装Monterey版本，进入安装程序后发现笔记本自带地键盘不能使用，只能外插键盘，是否是驱动不匹配？

**Comment by LoveGlaze** [comment]
自带小键盘查看小键盘修复命令

**Comment by LanJD** [comment]
> 自带小键盘查看小键盘修复命令

并非小键盘，是所有按键都无法使用

**Comment by LoveGlaze** [comment]
好像还有个ps2的键盘驱动，你加上试试，我没注意这个问题

**Comment by LanJD** [comment]
> 好像还有个ps2的键盘驱动，你加上试试，我没注意这个问题

好的 多谢

**Comment by LoveGlaze** [comment]
> 

还有就是注意一下键盘驱动的顺序，你可以加群问，懒得墙出来
