### ISSUE TITLE
有时冻屏，鼠标键盘无法操作

### ISSUE THREAD

**Issue by ipangbo** [gclm/Hackintosh-LEGION-Y7000P-I7-9750H#41]
在y7000p 2019 i7机型上使用Mac OS 12.5.1经常死机，屏幕冻住，鼠标键盘均不能操作，只能强制关机。大约每小时发生一回。请问是正常现象吗？

**Comment by LoveGlaze** [comment]
电脑是否存在pm981a系列硬盘，如果有请屏蔽，即使安装在别的盘上

**Comment by LoveGlaze** [comment]
> 在y7000p 2019 i7机型上使用Mac OS 12.5.1经常死机，屏幕冻住，鼠标键盘均不能操作，只能强制关机。大约每小时发生一回。请问是正常现象吗？

电脑是否存在pm981a系列硬盘，如果有请屏蔽，即使安装在别的盘上

**Comment by ipangbo** [comment]
> > 在y7000p 2019 i7机型上使用Mac OS 12.5.1经常死机，屏幕冻住，鼠标键盘均不能操作，只能强制关机。大约每小时发生一回。请问是正常现象吗？
> 
> 电脑是否存在pm981a系列硬盘，如果有请屏蔽，即使安装在别的盘上

电脑自带pm981a，已经换成西数SN570。但是死机的症状跟插入装了pm981a的固态硬盘盒死机的症状一模一样。

**Comment by LoveGlaze** [comment]
> > > 在y7000p 2019 i7机型上使用Mac OS 12.5.1经常死机，屏幕冻住，鼠标键盘均不能操作，只能强制关机。大约每小时发生一回。请问是正常现象吗？
> > 
> > 
> > 电脑是否存在pm981a系列硬盘，如果有请屏蔽，即使安装在别的盘上
> 
> 电脑自带pm981a，已经换成西数SN570。但是死机的症状跟有一次插入装了pm981a的固态硬盘盒死机的症状一模一样。

我随便爬了下贴，冻屏也有好些原因，因为此EFI我使用的过程中未出现此问题，你可以尝试更新引导和驱动，仍然出现试试去掉不必要的驱动，或是试试网上别的EFI

**Comment by ipangbo** [comment]
> > > > 在y7000p 2019 i7机型上使用Mac OS 12.5.1经常死机，屏幕冻住，鼠标键盘均不能操作，只能强制关机。大约每小时发生一回。请问是正常现象吗？
> > > 
> > > 
> > > 电脑是否存在pm981a系列硬盘，如果有请屏蔽，即使安装在别的盘上
> > 
> > 
> > 电脑自带pm981a，已经换成西数SN570。但是死机的症状跟有一次插入装了pm981a的固态硬盘盒死机的症状一模一样。
> 
> 我随便爬了下贴，冻屏也有好些原因，因为此EFI我使用的过程中未出现此问题，你可以尝试更新引导和驱动，仍然出现试试去掉不必要的驱动，或是试试网上别的EFI

我也试过另一个人的y7000系列的efi，同样也会死机。我现在正在排查换过的内存、网卡、硬盘。您看这样有意义吗，死机的问题是属于硬件问题还是软件问题？

**Comment by LoveGlaze** [comment]
也有可能系统问题，我看远景有一条原因是因为显存回收什么的也会，你可以找个监控软件看看显存运行情况，可以的话群里说吧，懒得墙出来

**Comment by ipangbo** [comment]
找到原因，因为使用了BCM943602CS网卡，换回原机自带的网卡后正常。
