### ISSUE TITLE
👍  大部分功能正常   一些小问题 

### ISSUE THREAD

**Issue by AlliotTech** [gclm/Hackintosh-LEGION-Y7000P-I7-9750H#9]
- 深度休眠容易睡死  
- 小键盘打了补丁后正常使用  不过开机不会自动锁定 需要手动锁定  
- 触控板的实体键不正常  其他正常  
- 声道不对，需要调成全左或者全右声道   当然也只是勉强能听  
- Wi-Fi 自带不能正常驱动，换成便宜的 USB 网卡 cf-wu810n  勉强能用  
- HDMI 和 Type-C 转接都无法使用显卡，据说是因为都是走的独立显卡的通道   不知道有没有人有  USB转HDMI推荐的

**Comment by gclm** [comment]
谢谢支持，目前该配置在我电脑上完美，所以在使用过程中需要根据自己电脑的情况进行微调
